//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "album_album_join")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub parent_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub album_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Albums2,
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::ParentId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Albums1,
}

impl ActiveModelBehavior for ActiveModel {}
