//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub album_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_photo_join::Entity")]
    AlbumPhotoJoin,
    #[sea_orm(has_many = "super::sharing_states::Entity")]
    SharingStates,
}

impl Related<super::album_photo_join::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumPhotoJoin.def()
    }
}

impl Related<super::sharing_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SharingStates.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        super::album_photo_join::Relation::Photos.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::album_photo_join::Relation::Albums.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
