//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "assets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub parent_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail_path: Option<String>,
    #[sea_orm(unique)]
    pub hash: String,
    pub file_name: String,
    pub size_on_disk: i64,
    pub photo_date: DateTimeUtc,
    pub photo_timezone: String,
    pub resolution_width: i64,
    pub resolution_height: i64,
    pub mime_type: String,
    pub camera_model: String,
    pub lens_model: String,
    pub shutter_count: i64,
    pub focal_length: i16,
    pub iso: i64,
    pub shutter_speed: String,
    #[sea_orm(column_type = "Float")]
    pub aperture: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collections::Entity",
        from = "Column::ParentId",
        to = "super::collections::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Collections,
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
