//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod album_album_join;
pub mod album_photo_join;
pub mod albums;
pub mod photos;
pub mod sharing_states;
pub mod thumbnails;
