//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "photos")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub hash: String,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    pub size_on_disk: i64,
    #[sea_orm(column_type = "Text")]
    pub photo_date: String,
    #[sea_orm(column_type = "Text")]
    pub photo_timezone: String,
    pub resolution_width: i64,
    pub resolution_height: i64,
    #[sea_orm(column_type = "Text")]
    pub mime_type: String,
    #[sea_orm(column_type = "Text")]
    pub camera_model: String,
    #[sea_orm(column_type = "Text")]
    pub lens_model: String,
    pub shutter_count: i64,
    pub focal_length: i64,
    pub iso: i64,
    #[sea_orm(column_type = "Text")]
    pub shutter_speed: String,
    #[sea_orm(column_type = "Double")]
    pub aperture: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_photo_join::Entity")]
    AlbumPhotoJoin,
    #[sea_orm(has_many = "super::sharing_states::Entity")]
    SharingStates,
    #[sea_orm(has_one = "super::thumbnails::Entity")]
    Thumbnails,
}

impl Related<super::album_photo_join::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumPhotoJoin.def()
    }
}

impl Related<super::sharing_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SharingStates.def()
    }
}

impl Related<super::thumbnails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Thumbnails.def()
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::album_photo_join::Relation::Albums.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::album_photo_join::Relation::Photos.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
