//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::album_album_join::Entity as AlbumAlbumJoin;
pub use super::album_photo_join::Entity as AlbumPhotoJoin;
pub use super::albums::Entity as Albums;
pub use super::photos::Entity as Photos;
pub use super::sharing_states::Entity as SharingStates;
pub use super::thumbnails::Entity as Thumbnails;
