use crate::db::schema::albums;
use diesel::prelude::*;
use rocket::serde::{Deserialize, Serialize};
use sea_orm::DerivePartialModel;

/// Represents an album with a unique identifier and name.
///
/// # Fields
/// * `id`: Album's unique ID, serialized as `albumId` in JSON
/// * `album_name`: Album name
///
/// # Example
/// ```
/// let album = Album {
///     id: 1,
///     album_name: "Vacation".into(),
/// };
/// ```
#[derive(DerivePartialModel, Queryable, Selectable, AsChangeset, Serialize, Deserialize, Debug)]
#[sea_orm(entity = "crate::db::entities::albums::Entity")]
#[serde(rename_all = "camelCase")]
pub struct Album {
    #[serde(rename = "albumId")]
    pub id: String,
    pub album_name: String
}


/// Represents an album as a tree node.
///
/// # Fields
/// * `id`: UUIDv7, serialized as `albumId` in JSON
/// * `album_name`: Album name
/// * `children`: Vec of child albums
///
/// # Example
/// ```
/// let album = Album {
///     id: 1,
///     album_name: "Vacation".into(),
///     children: vec![]
/// };
/// ```
#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct AlbumTree {
    #[serde(rename = "albumId")]
    pub id: String,
    pub album_name: String,
    pub children: Vec<AlbumTree>
}

impl From<Album> for AlbumTree {
    fn from(album: Album) -> Self {
        AlbumTree {
            id: album.id,
            album_name: album.album_name,
            children: vec![]
        }
    }
}


/// A variant of `Album` without photos or ID, used for creating new album instances.
///
/// This struct only contains the album name since IDs are auto-generated by the database
/// and photos are associated separately. It's primarily used when creating new albums
/// or updating album metadata.
///
/// # Fields
/// * `album_name`: The name for the new album
///
/// # Example
/// ```
/// let new_album = NewAlbum {
///     album_name: "Vacation Photos".into()
/// };
/// ```
#[derive(DerivePartialModel, Insertable, Deserialize, Debug)]
#[sea_orm(entity = "crate::db::entities::albums::Entity")]
#[serde(rename_all = "camelCase")]
#[diesel(table_name = albums)]
pub struct NewAlbum {
    pub album_name: String,
}
